### PR TITLE
Update zh_CN.lang to 5.1.5

### PR DESCRIPTION
**Pull request by ShieLian**

### CODE REVIEW

**Comment by 3TUSK** [comment]
@ShieLian I have a question: why not classical Chinese?

**Comment by ShieLian** [comment]
@3TUSK Too obscure and a little confused.

**Comment by 3TUSK** [comment]
@ShieLian Then those context lost mystical concept... whatsoever.

**Comment by ShieLian** [comment]
@3TUSK Oh,  I polished it according to the original text. By the way, I don't think too obscure to read and understand should be the price of the mysterious sense. If you want, help to find a balance between them, thanks.

**Pull request merged**
