### PR TITLE
Update ko_KR.lang 5.2.4

### PR DESCRIPTION
**Pull request by akrWkddl**
중간 저장용..계속 할게요..!

### CODE REVIEW

**Comment by akrWkddl** [comment]
still in progress..
please do not merge this yet...

**Comment by Azanor** [comment]
Cool, let me know when it is ready.

**Comment by akrWkddl** [comment]
골렘학만 남았다...힘내자 막짱아..!!

**Comment by akrWkddl** [comment]
all done!!
please merge this!!

**Comment by akrWkddl** [comment]
umm..is not merged yet..?

**Pull request merged**
